### ISSUE TITLE
can't identity language specific tests in subdirectories

### ISSUE THREAD

**Issue by njohnson-tw** [hawkeyesec/scanner-cli#52]
Hawkeye wasn't scanning my ruby app located in a subdirectory of my repo:

[info] Not Handling Brakeman Scan
[info] Not Handling Bundler Scan

... until I scoped the scan specifically to the subdirectory where the Gemfile is

[info] Running module Brakeman Scan
[info]  -> brakeman . -f json -o /target/inventory_web/output.json
[info] Running module Bundler Scan
[info] Updating bundler-audit database...
[info]  -> bundle-audit update
[info]  -> bundle-audit 

So the language specific tests don't appear to work in subdirectories.

Please advise, Thanks,
Nate

**Comment by felixhammerl** [comment]
Hi Nate,

as seen in the discussion on https://github.com/hawkeyesec/scanner-cli/pull/55, i would prefer to assume that the package descriptor is in the project's top level. For the sake of simplicity. And because lazy :)

Is it common for python projects to have things split up like that, or are those in fact separate projects? For separate project, I would recommend running separately scoped scans.

Assuming you'd be running `piprot`, `safety`, and `bandit` without the scanner, how would you run it normally?

I think the modules should stick to the language's convention as much as possible.

**Comment by felixhammerl** [comment]
Closing this for now...

**Comment by njohnson-tw** [comment]
Hi Felix, I've read through both issues. I do not know if it is common for ruby projects to have things split up like that. Maybe if the issue persists, maybe a note in the Hawkeye README file could be added to help developers structure their git repos in such a way as to get the best results from Hawkeye?

**Comment by felixhammerl** [comment]
Thanks for the pointer. Included some information about the project structure in the README.
